all:
  hosts:
    c4-master01:
      ansible_host: 172.16.4.11
      ip: 172.16.4.11
      access_ip: 172.16.4.11
    c4-master02:
      ansible_host: 172.16.4.12
      ip: 172.16.4.12
      access_ip: 172.16.4.12
    c4-master03:
      ansible_host: 172.16.4.13
      ip: 172.16.4.13
      access_ip: 172.16.4.13
    c4-node01:
      ansible_host: 172.16.4.14
      ip: 172.16.4.14
      access_ip: 172.16.4.14
    c4-node02:
      ansible_host: 172.16.4.15
      ip: 172.16.4.15
      access_ip: 172.16.4.15
    c4-node03:
      ansible_host: 172.16.4.16
      ip: 172.16.4.16
      access_ip: 172.16.4.16
    c4-node04:
      ansible_host: 172.16.4.17
      ip: 172.16.4.17
      access_ip: 172.16.4.17
    c4-node05:
      ansible_host: 172.16.4.18
      ip: 172.16.4.18
      access_ip: 172.16.4.18
    c4-node06:
      ansible_host: 172.16.4.19
      ip: 172.16.4.19
      access_ip: 172.16.4.19
  children:
    kube-master:
      hosts:
        c4-master01:
          vrrp_instance_state: MASTER
          vrrp_instance_priority: 101
        c4-master02:
          vrrp_instance_state: BACKUP
          vrrp_instance_priority: 100
        c4-master03:
          vrrp_instance_state: BACKUP
          vrrp_instance_priority: 99
      vars:
        vrrp_interface: ens4
        vrrp_instance_virtual_router_id: 104
    kube-node:
      hosts:
        c4-node01:
        c4-node02:
        c4-node03:
        c4-node04:
        c4-node05:
        c4-node06:
    etcd:
      hosts:
        c4-master01:
        c4-master02:
        c4-master03:
    k8s_cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
