all:
  hosts:
    c3-master01:
      ansible_host: 172.16.3.11
      ip: 172.16.3.11
      access_ip: 172.16.3.11
    c3-master02:
      ansible_host: 172.16.3.12
      ip: 172.16.3.12
      access_ip: 172.16.3.12
    c3-master03:
      ansible_host: 172.16.3.13
      ip: 172.16.3.13
      access_ip: 172.16.3.13
    c3-node01:
      ansible_host: 172.16.3.14
      ip: 172.16.3.14
      access_ip: 172.16.3.14
    c3-node02:
      ansible_host: 172.16.3.15
      ip: 172.16.3.15
      access_ip: 172.16.3.15
    c3-node03:
      ansible_host: 172.16.3.16
      ip: 172.16.3.16
      access_ip: 172.16.3.16
    c3-node04:
      ansible_host: 172.16.3.17
      ip: 172.16.3.17
      access_ip: 172.16.3.17
    c3-node05:
      ansible_host: 172.16.3.18
      ip: 172.16.3.18
      access_ip: 172.16.3.18
    c3-node06:
      ansible_host: 172.16.3.19
      ip: 172.16.3.19
      access_ip: 172.16.3.19
  children:
    kube-master:
      hosts:
        c3-master01:
          vrrp_instance_state: MASTER
          vrrp_instance_priority: 101
        c3-master02:
          vrrp_instance_state: BACKUP
          vrrp_instance_priority: 100
        c3-master03:
          vrrp_instance_state: BACKUP
          vrrp_instance_priority: 99
      vars:
        vrrp_interface: ens4
        vrrp_instance_virtual_router_id: 103
    kube-node:
      hosts:
        c3-node01:
        c3-node02:
        c3-node03:
        c3-node04:
        c3-node05:
        c3-node06:
    etcd:
      hosts:
        c3-master01:
        c3-master02:
        c3-master03:
    k8s_cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
